### ISSUE TITLE
Android Error

### ISSUE THREAD

**Issue by skyride99** [APSL/react-native-button#17]
Using RN 18.1, I get this error?

<img width="547" alt="screen shot 2016-01-28 at 10 27 23 pm" src="https://cloud.githubusercontent.com/assets/3801142/12649862/5e6d7438-c61b-11e5-825c-16c7722b3ff1.png">

**Comment by alvaromb** [comment]
Thanks for the bug report @skyride99! Will take a look :)

**Comment by alvaromb** [comment]
Oh! by 0.18.1 you mean https://github.com/facebook/react-native/releases/tag/v0.19.0-rc ?

**Comment by skyride99** [comment]
Its in package.json as 18.1 I did not update it. Just a regular react-native init. 

I tried on RN 17 also same problem.

**Comment by skyride99** [comment]
This works in iOS but not Android.
<Button
            style={styles.greenButton} textStyle={styles.textStyle}
            onPress={() => {
              console.log('sign in!')
            }}>
            Sign in
          </Button>

**Comment by alvaromb** [comment]
@skyride99 which Android version are you running on? I think that this happens under 4.3 or lower.

**Comment by alvaromb** [comment]
Ok, got it, you have to use a device with Android API 21+: https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableNativeFeedback.android.js#L99-L100

Will change a few things to make the ``background`` prop optional.

**Comment by alvaromb** [comment]
Solved in https://github.com/APSL/react-native-button/releases/tag/v2.4.1.

You'll see a warning, it's due to this react-native issue https://github.com/facebook/react-native/commit/28c0240361de2ce88f69822c3a8400f0edafe7a9

Thanks!

**Comment by alvaromb** [comment]
@bartonhammond you should update your fork with this version, fixes a problem with Android devices with API lower than 21.

**Comment by bartonhammond** [comment]
Thanks for thinking of me, but No bueno, running ```npm test```

```
 FAIL  src/components/__tests__/FormButton-test.js 
● Runtime Error
TypeError: Cannot read property 'style' of undefined
    at Object.eval (/Users/barton/projects/MFV/snowflake/node_modules/apsl-react-native-button/Button.js:19:25)
    at Loader._execModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:206:17)
    at Loader.requireModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at Loader.requireModuleOrMock (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:790:19)
    at Object.eval (/Users/barton/projects/MFV/snowflake/src/components/FormButton.js:22:12)
    at Loader._execModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:206:17)
    at Loader.requireModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at Loader.requireModuleOrMock (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:790:19)
    at Object.eval (/Users/barton/projects/MFV/snowflake/src/components/__tests__/FormButton-test.js:27:16)
    at Loader._execModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:206:17)
    at Loader.requireModule (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at jasmine1 (/Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/testRunners/jasmine/jasmine1.js:233:16)
    at /Users/barton/projects/MFV/snowflake/node_modules/jest-cli/src/TestRunner.js:261:14
 FAIL  src/components/__tests__/Header-test.js 
```

**Comment by alvaromb** [comment]
This version has the same problem with the style prop in Jest @bartonhammond, but makes the component usable with Android devices using older API versions. Update your fork if you want support with older Android versions. 

Enviado desde mi iPhone
