### ISSUE TITLE
Default Jest test is failing

### ISSUE THREAD

**Issue by voronianski** [APSL/react-native-button#53]
This is default test for view which is generated by `react-native init ProjectName` command:

```js
import 'react-native';
import React from 'react';
import Index from '../index.ios.js';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  const tree = renderer.create(
    <Index />
  );
});
```

In my index file I started to use `<Button>` component and it works awesomely fine in simulator. However when I ran test command I had a failed test with exception:

```bash
 dmitri@MacBook-Pro-Dmitri  ~/github/fanburst/FanburstApp   master  npm test

> FanburstApp@0.0.1 test /Users/dmitri/github/fanburst/FanburstApp
> jest

 PASS  __tests__/index.android.js (6.547s)
 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    /Users/dmitri/github/fanburst/FanburstApp/node_modules/apsl-react-native-button/Button.js:53
              <Text
              ^
    SyntaxError: Unexpected token <

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:284:10)
      at Object.<anonymous> (index.ios.js:17:28)
      at Object.<anonymous> (__tests__/index.ios.js:3:15)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        9.343s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Any ideas?

**Comment by alvaromb** [comment]
Hi @voronianski!

I have no idea, Jest test are working fine in the component, please double check your Jest configuration. Closing by now, seems more a Jest/test environment issue. Please let me know if you find the solution.
